### ISSUE TITLE
 Ingress: deprecated beta API removed in K8s 1.22

### ISSUE THREAD

**Issue by euklein** [RasaHQ/rasa-x-helm#253] opened 2021-12-06 13:47 UTC
The Ingress beta API was removed in K8s 1.22 (https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis). Should be probably updated, see https://github.com/RasaHQ/rasa-x-helm/blob/4b62ed6b0815136196dcbf7bf8f9a640e15d5047/charts/rasa-x/templates/ingress.yaml#L9

Using server version 1.22.4 of K8s, the installation of Rasa X was failing with the following error message:

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"

As a work around had to disable ingress during installation.

**Comment by tmbo** [comment] 2021-12-13 09:39
@virtualroot naive me thinks this is a small change - what do you think?

**Comment by virtualroot** [comment] 2021-12-31 03:12
@euklein I'm unable to reproduce the error.

I tried it with Rasa X Chart v2.11.0 on Kubernetes v1.22.3 with Helm v3.7.2.
`helm template` output picks the right API version.

```
# Source: rasa-x/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
...
```

NGINX controller logs seems fine and `curl --resolve 'rasa-x.example.com:80:127.0.0.1' rasa-x.example.com` works too.
```
W1231 02:48:00.797305       7 controller.go:1047] Service "default/rasa-x-nginx" does not have any active Endpoint.
I1231 02:48:01.125502       7 main.go:101] "successfully validated configuration, accepting" ingress="rasa-x/default"
I1231 02:48:01.155395       7 store.go:371] "Found valid IngressClass" ingress="default/rasa-x" ingressclass="nginx"
I1231 02:48:01.155751       7 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"rasa-x", UID:"2625ec44-316b-4adb-8c7d-d81408b9fcf6", APIVersion:"networking.k8s.io/v1", ResourceVersion:"911", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
W1231 02:48:03.756472       7 controller.go:1047] Service "default/rasa-x-nginx" does not have any active Endpoint.
I1231 02:48:03.756550       7 controller.go:152] "Configuration changes detected, backend reload required"
I1231 02:48:03.817346       7 controller.go:169] "Backend successfully reloaded"
I1231 02:48:03.817981       7 event.go:282] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ingress-nginx", Name:"ingress-nginx-controller-5f66978484-gdszj", UID:"5344f8d7-1632-4a38-b0ac-e4a9537e53cb", APIVersion:"v1", ResourceVersion:"525", FieldPath:""}): type: 'Normal' reason: 'RELOAD' NGINX reload triggered due to a change in configuration
W1231 02:48:07.087123       7 controller.go:1047] Service "default/rasa-x-nginx" does not have any active Endpoint.
W1231 02:48:25.961691       7 controller.go:1047] Service "default/rasa-x-nginx" does not have any active Endpoint.
I1231 02:48:33.619331       7 status.go:300] "updating Ingress status" namespace="default" ingress="rasa-x" currentValue=[] newValue=[{IP: Hostname:localhost Ports:[]}]
W1231 02:48:33.625992       7 controller.go:1047] Service "default/rasa-x-nginx" does not have any active Endpoint.
I1231 02:48:33.626572       7 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"rasa-x", UID:"2625ec44-316b-4adb-8c7d-d81408b9fcf6", APIVersion:"networking.k8s.io/v1", ResourceVersion:"1000", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
W1231 02:48:40.895751       7 controller.go:1047] Service "default/rasa-x-nginx" does not have any active Endpoint.
```

From what I see in the documentation, `.Capabilities.KubeVersion.Version` is available in [Helm v3](https://helm.sh/docs/chart_template_guide/builtin_objects/) but not in [Helm v2](https://v2.helm.sh/docs/chart_template_guide/#built-in-objects).
Is it possible you are using Helm v2?

**Comment by euklein** [comment] 2022-01-03 08:24
@virtualroot Yes, this error was strange. I only got it when the server version of K8s was 1.22.4. The 4 for the minor version is important. With 1.22.3 the installation worked for me too. I was using Helm 3.7 in both cases.

**Comment by virtualroot** [comment] 2022-01-11 15:28
@euklein I tried again with v1.22.4 and I can't replicate the issue.

`minikube start --disk-size='80000mb' --driver='hyperkit' --vm=true --kubernetes-version=v1.22.4`

Do you have a custom values.yml file? if so, can you share it?

**Comment by virtualroot** [comment] 2022-01-18 10:28
Since I haven't been able to reproduce this issue, I'm closing it.

@euklein ping me over Slack if you still see it, lets e-meet and try to solve it together.

**Closed by virtualroot** 2022-01-18 10:28 UTC
Labels: area:rasa-x/infrastructure :steam_locomotive:, type:maintenance :wrench:
